name: Build And Test

on: [push, pull_request]

jobs:
# https://github.com/apple/swift-nio/blob/main/.github/workflows/unit_tests.yml
  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false
      linux_6_0_enabled: true
      # this currently resolves to 6.1 nightly
      linux_6_0_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_next_enabled: true
      linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error"
      # this currently resolves to 6.2.dev
      # It crashes some of our tests https://github.com/swift-server/swift-aws-lambda-runtime/issues/509
      linux_nightly_main_enabled: true
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error"

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_enabled: true
      license_header_check_project_name: "Swift Foundation Models Playground"
      shell_check_enabled: false
      python_lint_check_enabled: false
      api_breakage_check_enabled: false
      docs_check_container_image: "swift:6.0-noble"
      format_check_container_image: "swift:6.0-noble"
      yamllint_check_enabled: true
