name: Build And Test

on: [push, pull_request]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  

  jobs:
  setup-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenSSL and ICU
        run: sudo apt-get update && sudo apt-get install -y libssl-dev libicu-dev

  unit-tests:
    name: Unit tests
    needs: setup-dependencies
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false
      linux_6_0_enabled: true
      linux_6_0_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_next_enabled: true
      linux_nightly_next_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_main_enabled: true
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error"

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_enabled: true
      license_header_check_project_name: "Swift Foundation Models Playground"
      shell_check_enabled: false
      python_lint_check_enabled: false
      api_breakage_check_enabled: false
      docs_check_container_image: "swift:6.0-noble"
      format_check_container_image: "swift:6.0-noble"
      yamllint_check_enabled: true
